import { describe, it, expect } from "vitest";
import { parseCandidatesCSV, generateSampleCSV } from "./csv-parser";

describe("parseCandidatesCSV", () => {
  it("should parse a valid CSV with standard headers", () => {
    const csv = `full_name,email,phone\nJohn Doe,john@example.com,1234567890`;
    const result = parseCandidatesCSV(csv);

    expect(result.headers).toEqual(["full_name", "email", "phone"]);
    expect(result.candidates).toHaveLength(1);
    expect(result.candidates[0]).toEqual(
      expect.objectContaining({
        full_name: "John Doe",
        email: "john@example.com",
        phone: "1234567890",
      })
    );
  });

  it("should handle the sample CSV generated by generateSampleCSV", () => {
    const csv = generateSampleCSV();
    const result = parseCandidatesCSV(csv);

    expect(result.headers).toEqual(["Name", "Email", "Phone", "Location", "Experience", "Education"]);
    expect(result.candidates).toHaveLength(1);
    expect(result.candidates[0]).toEqual(
      expect.objectContaining({
        full_name: "John Doe",
        email: "john@example.com",
        phone: "+1234567890",
        location: "New York",
        experience: "5 years",
        education: "B.Tech CS",
        name: "John Doe"
      })
    );
  });

  it("should return empty results for empty or single-line CSV", () => {
    const emptyResult = parseCandidatesCSV("");
    expect(emptyResult).toEqual({ headers: [], candidates: [] });

    const singleLineResult = parseCandidatesCSV("full_name,email,phone");
    expect(singleLineResult).toEqual({ headers: [], candidates: [] });
  });

  it("should normalize headers", () => {
    const csv = `Full Name, E-Mail Address, Phone Number\nJane Doe, jane@example.com, 0987654321`;
    const result = parseCandidatesCSV(csv);

    expect(result.headers).toEqual(["Full Name", "E-Mail Address", "Phone Number"]);
    expect(result.candidates).toHaveLength(1);
    // Because it maps lowercase headers
    expect(result.candidates[0]).toHaveProperty("full_name", "Jane Doe"); // fallback to values[0]
    expect(result.candidates[0]).toHaveProperty("e-mail_address", "jane@example.com");
    expect(result.candidates[0]).toHaveProperty("phone_number", "0987654321");
    // falls back email to values[1]
    expect(result.candidates[0]).toHaveProperty("email", "jane@example.com");
  });

  it("should fallback full_name to name or first column", () => {
    // Falls back to name
    const csv1 = `name,email\nAlice,alice@example.com`;
    const result1 = parseCandidatesCSV(csv1);
    expect(result1.candidates[0].full_name).toBe("Alice");

    // Falls back to first column
    const csv2 = `col1,email\nBob,bob@example.com`;
    const result2 = parseCandidatesCSV(csv2);
    expect(result2.candidates[0].full_name).toBe("Bob");
  });

  it("should fallback email to 'email' column or second column", () => {
    // Falls back to second column
    const csv = `name,contact\nCharlie,charlie@example.com`;
    const result = parseCandidatesCSV(csv);
    expect(result.candidates[0].email).toBe("charlie@example.com");
  });

  it("should filter out rows without both full_name and email (after fallbacks)", () => {
    const csv = "name,email\nValid Name,valid@example.com\nInvalid Name, \n ,invalid@example.com\n , ";
    const result = parseCandidatesCSV(csv);

    expect(result.candidates).toHaveLength(1);
    expect(result.candidates[0].full_name).toBe("Valid Name");
    expect(result.candidates[0].email).toBe("valid@example.com");
  });

  it("should handle edge cases with missing values or fewer columns than headers", () => {
    const csv = `col1,col2,col3\nval1,val2`;
    const result = parseCandidatesCSV(csv);

    expect(result.candidates).toHaveLength(1);
    expect(result.candidates[0].col1).toBe("val1");
    expect(result.candidates[0].col2).toBe("val2");
    expect(result.candidates[0].col3).toBe(""); // Missing values map to ''
    expect(result.candidates[0].full_name).toBe("val1"); // fallback to values[0]
    expect(result.candidates[0].email).toBe("val2"); // fallback to values[1]
  });

  it("should handle empty lines gracefully", () => {
    const csv = `name,email\n\nJohn,john@example.com\n\nJane,jane@example.com\n`;
    const result = parseCandidatesCSV(csv);

    expect(result.candidates).toHaveLength(2);
  });
});
