-- Migration: 20260924021000_index_foreign_keys_and_add_pks.sql
-- Description: Add primary keys to KPI score/settings tables and index unindexed foreign keys

-- 1. ADD PRIMARY KEYS TO KPI TABLES
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid = 'public.kpi_settings'::regclass AND contype = 'p') THEN
    ALTER TABLE public.kpi_settings ADD PRIMARY KEY (id);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid = 'public.kpi_quarterly_scores'::regclass AND contype = 'p') THEN
    ALTER TABLE public.kpi_quarterly_scores ADD PRIMARY KEY (id);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid = 'public.kpi_monthly_scores'::regclass AND contype = 'p') THEN
    ALTER TABLE public.kpi_monthly_scores ADD PRIMARY KEY (id);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid = 'public.kpi_daily_scores'::regclass AND contype = 'p') THEN
    ALTER TABLE public.kpi_daily_scores ADD PRIMARY KEY (id);
  END IF;
END $$;


-- 2. COVERING INDEXES FOR UNINDEXED FOREIGN KEYS (127)
CREATE INDEX IF NOT EXISTS idx_profiles_manager_id ON public.profiles (manager_id);
CREATE INDEX IF NOT EXISTS idx_roles_company_id ON public.roles (company_id);
CREATE INDEX IF NOT EXISTS idx_role_permissions_role_id ON public.role_permissions (role_id);
CREATE INDEX IF NOT EXISTS idx_user_roles_assigned_by ON public.user_roles (assigned_by);
CREATE INDEX IF NOT EXISTS idx_user_roles_role_id ON public.user_roles (role_id);
CREATE INDEX IF NOT EXISTS idx_departments_company_id ON public.departments (company_id);
CREATE INDEX IF NOT EXISTS idx_departments_parent_id ON public.departments (parent_id);
CREATE INDEX IF NOT EXISTS idx_designations_company_id ON public.designations (company_id);
CREATE INDEX IF NOT EXISTS idx_designations_department_id ON public.designations (department_id);
CREATE INDEX IF NOT EXISTS idx_employees_designation_id ON public.employees (designation_id);
CREATE INDEX IF NOT EXISTS idx_employees_location_id ON public.employees (location_id);
CREATE INDEX IF NOT EXISTS idx_employees_reporting_manager_id ON public.employees (reporting_manager_id);
CREATE INDEX IF NOT EXISTS idx_invitations_company_id ON public.invitations (company_id);
CREATE INDEX IF NOT EXISTS idx_invitations_invited_by ON public.invitations (invited_by);
CREATE INDEX IF NOT EXISTS idx_invitations_role_id ON public.invitations (role_id);
CREATE INDEX IF NOT EXISTS idx_attendance_location_id ON public.attendance (location_id);
CREATE INDEX IF NOT EXISTS idx_shifts_company_id ON public.shifts (company_id);
CREATE INDEX IF NOT EXISTS idx_employee_shifts_employee_id ON public.employee_shifts (employee_id);
CREATE INDEX IF NOT EXISTS idx_employee_shifts_shift_id ON public.employee_shifts (shift_id);
CREATE INDEX IF NOT EXISTS idx_leave_types_company_id ON public.leave_types (company_id);
CREATE INDEX IF NOT EXISTS idx_leave_balances_employee_id ON public.leave_balances (employee_id);
CREATE INDEX IF NOT EXISTS idx_leave_balances_leave_type_id ON public.leave_balances (leave_type_id);
CREATE INDEX IF NOT EXISTS idx_leave_requests_approved_by ON public.leave_requests (approved_by);
CREATE INDEX IF NOT EXISTS idx_leave_requests_company_id ON public.leave_requests (company_id);
CREATE INDEX IF NOT EXISTS idx_leave_requests_leave_type_id ON public.leave_requests (leave_type_id);
CREATE INDEX IF NOT EXISTS idx_holidays_company_id ON public.holidays (company_id);
CREATE INDEX IF NOT EXISTS idx_pay_grades_company_id ON public.pay_grades (company_id);
CREATE INDEX IF NOT EXISTS idx_salary_structures_company_id ON public.salary_structures (company_id);
CREATE INDEX IF NOT EXISTS idx_salary_structures_employee_id ON public.salary_structures (employee_id);
CREATE INDEX IF NOT EXISTS idx_payroll_runs_company_id ON public.payroll_runs (company_id);
CREATE INDEX IF NOT EXISTS idx_payroll_runs_processed_by ON public.payroll_runs (processed_by);
CREATE INDEX IF NOT EXISTS idx_payslips_company_id ON public.payslips (company_id);
CREATE INDEX IF NOT EXISTS idx_payslips_employee_id ON public.payslips (employee_id);
CREATE INDEX IF NOT EXISTS idx_payslips_payroll_run_id ON public.payslips (payroll_run_id);
CREATE INDEX IF NOT EXISTS idx_goals_company_id ON public.goals (company_id);
CREATE INDEX IF NOT EXISTS idx_goals_created_by ON public.goals (created_by);
CREATE INDEX IF NOT EXISTS idx_goals_employee_id ON public.goals (employee_id);
CREATE INDEX IF NOT EXISTS idx_review_cycles_company_id ON public.review_cycles (company_id);
CREATE INDEX IF NOT EXISTS idx_performance_reviews_cycle_id ON public.performance_reviews (cycle_id);
CREATE INDEX IF NOT EXISTS idx_performance_reviews_reviewee_id ON public.performance_reviews (reviewee_id);
CREATE INDEX IF NOT EXISTS idx_performance_reviews_reviewer_id ON public.performance_reviews (reviewer_id);
CREATE INDEX IF NOT EXISTS idx_jobs_department_id ON public.jobs (department_id);
CREATE INDEX IF NOT EXISTS idx_jobs_posted_by ON public.jobs (posted_by);
CREATE INDEX IF NOT EXISTS idx_candidates_assigned_by ON public.candidates (assigned_by);
CREATE INDEX IF NOT EXISTS idx_candidates_assigned_to ON public.candidates (assigned_to);
CREATE INDEX IF NOT EXISTS idx_candidates_candidate_user_id ON public.candidates (candidate_user_id);
CREATE INDEX IF NOT EXISTS idx_candidates_company_id ON public.candidates (company_id);
CREATE INDEX IF NOT EXISTS idx_interviews_candidate_id ON public.interviews (candidate_id);
CREATE INDEX IF NOT EXISTS idx_courses_company_id ON public.courses (company_id);
CREATE INDEX IF NOT EXISTS idx_courses_created_by ON public.courses (created_by);
CREATE INDEX IF NOT EXISTS idx_course_enrollments_assigned_by ON public.course_enrollments (assigned_by);
CREATE INDEX IF NOT EXISTS idx_course_enrollments_course_id ON public.course_enrollments (course_id);
CREATE INDEX IF NOT EXISTS idx_course_enrollments_employee_id ON public.course_enrollments (employee_id);
CREATE INDEX IF NOT EXISTS idx_tickets_assigned_to ON public.tickets (assigned_to);
CREATE INDEX IF NOT EXISTS idx_tickets_raised_by ON public.tickets (raised_by);
CREATE INDEX IF NOT EXISTS idx_ticket_comments_author_id ON public.ticket_comments (author_id);
CREATE INDEX IF NOT EXISTS idx_ticket_comments_ticket_id ON public.ticket_comments (ticket_id);
CREATE INDEX IF NOT EXISTS idx_announcements_company_id ON public.announcements (company_id);
CREATE INDEX IF NOT EXISTS idx_announcements_created_by ON public.announcements (created_by);
CREATE INDEX IF NOT EXISTS idx_announcement_reads_announcement_id ON public.announcement_reads (announcement_id);
CREATE INDEX IF NOT EXISTS idx_announcement_reads_employee_id ON public.announcement_reads (employee_id);
CREATE INDEX IF NOT EXISTS idx_surveys_company_id ON public.surveys (company_id);
CREATE INDEX IF NOT EXISTS idx_surveys_created_by ON public.surveys (created_by);
CREATE INDEX IF NOT EXISTS idx_survey_responses_respondent_id ON public.survey_responses (respondent_id);
CREATE INDEX IF NOT EXISTS idx_survey_responses_survey_id ON public.survey_responses (survey_id);
CREATE INDEX IF NOT EXISTS idx_notifications_company_id ON public.notifications (company_id);
CREATE INDEX IF NOT EXISTS idx_audit_logs_actor_id ON public.audit_logs (actor_id);
CREATE INDEX IF NOT EXISTS idx_offer_templates_company_id ON public.offer_templates (company_id);
CREATE INDEX IF NOT EXISTS idx_candidate_offers_candidate_id ON public.candidate_offers (candidate_id);
CREATE INDEX IF NOT EXISTS idx_candidate_offers_company_id ON public.candidate_offers (company_id);
CREATE INDEX IF NOT EXISTS idx_candidate_offers_job_id ON public.candidate_offers (job_id);
CREATE INDEX IF NOT EXISTS idx_candidate_offers_template_id ON public.candidate_offers (template_id);
CREATE INDEX IF NOT EXISTS idx_wallet_transactions_created_by ON public.wallet_transactions (created_by);
CREATE INDEX IF NOT EXISTS idx_employee_exits_company_id ON public.employee_exits (company_id);
CREATE INDEX IF NOT EXISTS idx_employee_exits_created_by ON public.employee_exits (created_by);
CREATE INDEX IF NOT EXISTS idx_gift_cards_redeemed_by ON public.gift_cards (redeemed_by);
CREATE INDEX IF NOT EXISTS idx_company_documents_company_id ON public.company_documents (company_id);
CREATE INDEX IF NOT EXISTS idx_company_documents_created_by ON public.company_documents (created_by);
CREATE INDEX IF NOT EXISTS idx_senddesk_templates_created_by ON public.senddesk_templates (created_by);
CREATE INDEX IF NOT EXISTS idx_senddesk_documents_created_by ON public.senddesk_documents (created_by);
CREATE INDEX IF NOT EXISTS idx_senddesk_documents_template_id ON public.senddesk_documents (template_id);
CREATE INDEX IF NOT EXISTS idx_senddesk_emails_created_by ON public.senddesk_emails (created_by);
CREATE INDEX IF NOT EXISTS idx_senddesk_emails_document_id ON public.senddesk_emails (document_id);
CREATE INDEX IF NOT EXISTS idx_senddesk_emails_employee_id ON public.senddesk_emails (employee_id);
CREATE INDEX IF NOT EXISTS idx_recruitment_team_members_manager_id ON public.recruitment_team_members (manager_id);
CREATE INDEX IF NOT EXISTS idx_recruitment_team_members_user_id ON public.recruitment_team_members (user_id);
CREATE INDEX IF NOT EXISTS idx_ai_interviews_candidate_id ON public.ai_interviews (candidate_id);
CREATE INDEX IF NOT EXISTS idx_ai_interviews_job_id ON public.ai_interviews (job_id);
CREATE INDEX IF NOT EXISTS idx_sprints_company_id ON public.sprints (company_id);
CREATE INDEX IF NOT EXISTS idx_tasks_assigned_by ON public.tasks (assigned_by);
CREATE INDEX IF NOT EXISTS idx_tasks_assigned_to ON public.tasks (assigned_to);
CREATE INDEX IF NOT EXISTS idx_tasks_company_id ON public.tasks (company_id);
CREATE INDEX IF NOT EXISTS idx_tasks_sprint_id ON public.tasks (sprint_id);
CREATE INDEX IF NOT EXISTS idx_task_time_logs_task_id ON public.task_time_logs (task_id);
CREATE INDEX IF NOT EXISTS idx_task_time_logs_user_id ON public.task_time_logs (user_id);
CREATE INDEX IF NOT EXISTS idx_daily_reports_company_id ON public.daily_reports (company_id);
CREATE INDEX IF NOT EXISTS idx_onboarding_steps_company_id ON public.onboarding_steps (company_id);
CREATE INDEX IF NOT EXISTS idx_onboarding_progress_completed_by ON public.onboarding_progress (completed_by);
CREATE INDEX IF NOT EXISTS idx_onboarding_progress_step_id ON public.onboarding_progress (step_id);
CREATE INDEX IF NOT EXISTS idx_onboarding_automations_company_id ON public.onboarding_automations (company_id);
CREATE INDEX IF NOT EXISTS idx_onboarding_document_requirements_company_id ON public.onboarding_document_requirements (company_id);
CREATE INDEX IF NOT EXISTS idx_onboarding_document_submissions_requirement_id ON public.onboarding_document_submissions (requirement_id);
CREATE INDEX IF NOT EXISTS idx_assets_assigned_employee_id ON public.assets (assigned_employee_id);
CREATE INDEX IF NOT EXISTS idx_assets_company_id ON public.assets (company_id);
CREATE INDEX IF NOT EXISTS idx_workflows_company_id ON public.workflows (company_id);
CREATE INDEX IF NOT EXISTS idx_workflow_runs_workflow_id ON public.workflow_runs (workflow_id);
CREATE INDEX IF NOT EXISTS idx_candidate_resume_embeddings_candidate_id ON public.candidate_resume_embeddings (candidate_id);
CREATE INDEX IF NOT EXISTS idx_candidate_resume_embeddings_company_id ON public.candidate_resume_embeddings (company_id);
CREATE INDEX IF NOT EXISTS idx_attrition_predictions_company_id ON public.attrition_predictions (company_id);
CREATE INDEX IF NOT EXISTS idx_attrition_predictions_employee_id ON public.attrition_predictions (employee_id);
CREATE INDEX IF NOT EXISTS idx_kudos_board_company_id ON public.kudos_board (company_id);
CREATE INDEX IF NOT EXISTS idx_kudos_board_receiver_id ON public.kudos_board (receiver_id);
CREATE INDEX IF NOT EXISTS idx_kudos_board_sender_id ON public.kudos_board (sender_id);
CREATE INDEX IF NOT EXISTS idx_pulse_logs_company_id ON public.pulse_logs (company_id);
CREATE INDEX IF NOT EXISTS idx_pulse_logs_department_id ON public.pulse_logs (department_id);
CREATE INDEX IF NOT EXISTS idx_company_locations_company_id ON public.company_locations (company_id);
CREATE INDEX IF NOT EXISTS idx_kpi_daily_scores_scored_by ON public.kpi_daily_scores (scored_by);
CREATE INDEX IF NOT EXISTS idx_kpi_monthly_scores_employee_id ON public.kpi_monthly_scores (employee_id);
CREATE INDEX IF NOT EXISTS idx_kpi_monthly_scores_scored_by ON public.kpi_monthly_scores (scored_by);
CREATE INDEX IF NOT EXISTS idx_kpi_quarterly_scores_employee_id ON public.kpi_quarterly_scores (employee_id);
CREATE INDEX IF NOT EXISTS idx_kpi_quarterly_scores_scored_by ON public.kpi_quarterly_scores (scored_by);
CREATE INDEX IF NOT EXISTS idx_global_employee_added_by_company_id ON public.global_employee (added_by_company_id);
CREATE INDEX IF NOT EXISTS idx_global_employee_added_by_user_id ON public.global_employee (added_by_user_id);
CREATE INDEX IF NOT EXISTS idx_meeting_event_types_company_id ON public.meeting_event_types (company_id);
CREATE INDEX IF NOT EXISTS idx_meeting_bookings_event_type_id ON public.meeting_bookings (event_type_id);
CREATE INDEX IF NOT EXISTS idx_meeting_bookings_rescheduled_from_id ON public.meeting_bookings (rescheduled_from_id);
CREATE INDEX IF NOT EXISTS idx_byos_audit_log_performed_by ON public.byos_audit_log (performed_by);
